version: '3.8'
services:
  tor:
    image: tor:0.4.7.13
    build:
      context: ./tor-source
      args:
        - TOR_VERSION=0.4.7.13
        - GROUP_ID=1002
    restart: on-failure
    volumes:
      - ./volumes/tor:/home/tor